---
title: "12.15.22 FB Data US W2"
output: html_document
date: "2022-12-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
usdata.wave2 <- read.csv("/Users/brianaitken/Desktop/Final US recontact dataset (EDITED) .csv")

library(dplyr)

usdata.wave2<- usdata.wave2 %>% mutate(gender= case_when( 
  gender == "Male" ~ 1, 
  gender == "Female" ~ 2
))




###Recoding Age Variable
usdata.wave2<- usdata.wave2 %>% mutate(age= case_when( 
  age == "18 to 24" ~ 1, 
  age == "25 to 34" ~ 2, 
  age == "35 to 44" ~ 3, 
  age == "45 to 54" ~ 4,
  age == "55 to 64" ~ 5, 
  age == "65+" ~ 6
))


usdata.wave2$age

##Recoding Race Variable 

usdata.wave2<- usdata.wave2 %>% mutate(race = case_when( 
  race == "American Indian or Alaskan Native" ~ 1, 
  race == "Hawaiian or other Pacific islander" ~ 2, 
  race == "Asian or Asian American" ~ 3, 
  race == "Black or African American" ~ 4,
  race == "Hispanic or Latino" ~ 5, 
  race == "Non-Hispanic White" ~ 6,
  race == "Other" ~ 7
))


###Recoding Education Variable 
usdata.wave2<- usdata.wave2 %>% mutate(education = case_when( 
  education == "Some High School or less" ~ 1, 
  education == "High School Graduate" ~ 2, 
  education == "Some College Complete" ~ 3, 
  education == "College Degree" ~ 4,
  education == "Master's Degree" ~ 5, 
  education == "Ph.D./Doctorate" ~ 6
))

###Recoding Party ID 
usdata.wave2<- usdata.wave2 %>% mutate(party.ID = case_when( 
  party.ID  == "A strong Democrat" ~ 1, 
  party.ID  == "A not very strong Democrat" ~ 2, 
  party.ID  == "Independent, lean toward Democrat" ~ 3, 
  party.ID  == "Independent (close to neither party)" ~ 4,
  party.ID  == "Independent, lean toward Republican" ~ 5,
  party.ID  == "A not very strong Republican" ~ 6,
  party.ID  == "A strong Republican" ~ 7
))

###Recoding Ideology Variable 
usdata.wave2<- usdata.wave2 %>% mutate(ideology = case_when( 
  ideology == "Very liberal" ~ 1, 
  ideology == "Somewhat liberal" ~ 2, 
  ideology == "Middle of the road" ~ 3, 
  ideology == "Somewhat conservative" ~ 4,
  ideology == "Very conservative" ~ 5
))

###Recoding Political Interest Variable 
usdata.wave2 <- usdata.wave2 %>% mutate(political_interest = case_when( 
  political_interest  == "Not at all interested" ~ 1, 
  political_interest  == "Not very interested" ~ 2, 
  political_interest  == "Somewhat interested" ~ 3, 
  political_interest  == "Very interested" ~ 4,
  political_interest  == "Extremely interested" ~ 5
))


###Recoding Click Variables 
usdata.wave2<- usdata.wave2 %>% mutate(NATIONALREPORT.COM = case_when( 
  NATIONALREPORT.COM  == "No" ~ 0, 
  NATIONALREPORT.COM  == "Yes" ~ 1
))

usdata.wave2<- usdata.wave2 %>% mutate(WORLDNEWSDAILYREPORT.COM = case_when( 
  WORLDNEWSDAILYREPORT.COM  == "No" ~ 0, 
  WORLDNEWSDAILYREPORT.COM  == "Yes" ~ 1
))

usdata.wave2<- usdata.wave2 %>% mutate(APNEWS.COM = case_when( 
  APNEWS.COM  == "No" ~ 0, 
  APNEWS.COM  == "Yes" ~ 1
))

usdata.wave2<- usdata.wave2 %>% mutate(USATODAY.COM = case_when( 
  USATODAY.COM  == "No" ~ 0, 
  USATODAY.COM  == "Yes" ~ 1
))

usdata.wave2<- usdata.wave2 %>% mutate(FACTCHECK.ORG = case_when( 
  FACTCHECK.ORG  == "No" ~ 0, 
  FACTCHECK.ORG  == "Yes" ~ 1
))

usdata.wave2<- usdata.wave2 %>% mutate(WASHINGTONPOST.COM = case_when( 
  WASHINGTONPOST.COM  == "No" ~ 0, 
  WASHINGTONPOST.COM  == "Yes" ~ 1
))


usdata.wave2<- usdata.wave2 %>% mutate(DIGITAL.COM = case_when( 
  DIGITAL.COM  == "No" ~ 0, 
  DIGITAL.COM  == "Yes" ~ 1
))


usdata.wave2<- usdata.wave2 %>% mutate(COMMONSENSE.ORG = case_when( 
  COMMONSENSE.ORG  == "No" ~ 0, 
  COMMONSENSE.ORG  == "Yes" ~ 1
))

usdata.wave2$To.check.whether.you.are.reading.the.questions..click.on.the.second.answer.from.the.top. <-usdata.wave2$attncheck

###Setting Variable Values and Labels 
if (!require("expss")) install.packages("expss")
library(expss)

###usdata.wave2 = apply_labels(usdata.wave2, 
                    #  gender = "1 Male 2 Female", 
                     # age = "18 to 24 = 1, 65+ = 6",
                   #   race = "American Indian or Alaskan Native = 1 Other = 7", 
                   #   education = "Some High School or less = 1 Ph.D./Doctorate = 6", 
                    #  ideology ="Very liberal = 1 Very conservative = 5", 
                      #party.ID = "A strong Democrat = 1 A strong Republican = 7", 
                     # political_interest = "Not at all interested = 1 Extremely interested = 5", 
                      #misp = "1 Low Misp 4 High Misp", 
                      #skept = " 1 Low trust 7 High trust", 
                      #hyperpartisan = "1 High detection  4 Low detection", 
                      #mainstream = "1 low detection 4 high detection",
                      #false = "1 High detection 4 Low detection",
                      #trust = " 1 Low trust 7 High trust", 
                      #tr_medialit = "0 = control 1 = bias 2 = misinfo", 
                      #tr_coverage = "0 = control 1 = contextualized 2 = de-contextualized", 
                      #tr_factcheck = "0 = control 1 = accountability 2 = correctability", 
                      #tr_all = "0 control 1 = contextualized 2 = de-contextualized 3 accountability 4 = correctability  5 = bias 6 = misinfo")


###Creating US misperceptionn variable 
usdata.wave2$misp <- (rowSums(usdata.wave2[,c("false1_acc", "false2_acc")], na.rm=TRUE))/2

###Creating US Skeptism variable
usdata.wave2$skept <- (rowSums(usdata.wave2[,c("true1_acc", "true2_acc", "true3_acc")], na.rm=TRUE))/3

###Recoding US Skeptism variable 
usdata.wave2$skept <- 5 - usdata.wave2$skept


###Creating Trust Variable 
usdata.wave2$trust <- (rowSums(usdata.wave2[,c("Journalists", "Fact.checkers", "U.S..Government", "University.Professors", 
                                   "Social.media", "Traditional.media", "Scientists")], na.rm=TRUE))/7
  

library(dplyr)

###Medialit treatment 
usdata.wave2<- usdata.wave2 %>% mutate(tr_medialit = case_when( 
  condition == "10" ~ 0, 
  condition == "8" ~ 1, 
  condition == "9" ~ 2
))


###Factchecking Treatment
usdata.wave2<- usdata.wave2 %>% mutate(tr_factcheck = case_when( 
  condition == "10" ~ 0, 
  condition == "3" ~ 1, 
  condition == "4" ~ 1,
  condition == "5" ~ 1,
  condition == "6" ~ 1,
  condition == "7" ~ 2
))


###Misinfo Coverage 
usdata.wave2<- usdata.wave2 %>% mutate(tr_coverage = case_when( 
  condition == "10" ~ 0, 
  condition == "1" ~ 1, 
  condition == "2" ~ 2
))

###Treatment All 
usdata.wave2 <- usdata.wave2 %>% mutate(tr_all = case_when( 
  condition == "10" ~ 0, 
  condition == "1" ~ 1, 
  condition == "2" ~ 2,
  condition == "3" ~ 3, 
  condition == "4" ~ 3,
  condition == "5" ~ 3,
  condition == "6" ~ 3,
  condition == "7" ~ 4,
  condition == "8" ~ 5, 
  condition == "9" ~ 6
))

###Creating Site Visit Counts by condition
usdata.wave2$visit_fact <- usdata.wave2$FACTCHECK.ORG + usdata.wave2$WASHINGTONPOST.COM
usdata.wave2$visit_fake <- usdata.wave2$NATIONALREPORT.COM + usdata.wave2$WORLDNEWSDAILYREPORT.COM
usdata.wave2$visit_news <- usdata.wave2$APNEWS.COM + usdata.wave2$USATODAY.COM
usdata.wave2$visit_medialit <- usdata.wave2$COMMONSENSE.ORG + usdata.wave2$DIGITAL.COM


###Creating hyperparisan score

usdata.wave2$hyperpartisan <- ((rowSums(usdata.wave2[,c("HL1_partisan_left_bias", "HL1_partisan_left_favor", "HL2_partisan_left_bias", "HL2_partisan_left_favor", 
                                   "HL3_partisan_left_bias", "HL3_partisan_left_favor", "HL4_partisan_left_bias", "HL4_partisan_left_favor", "HL5_partisan_left_bias", "HL5_partisan_left_favor", "HL6_partisan_left_biased", "HL6_partisan_left_favor", "HL1_partisan_right_biased", "HL1_partisan_right_favor", "HL2_partisan_right_bias", "HL2_partisan_right_favor", "HL3_partisan_right_bias", "HL3_partisan_right_favor", "HL4_partisan_right_bias", "HL4_partisan_right_favor", "HL5_partisan_right_bias", "HL5_partisan_right_favor", "HL6_partisan_right_bias", "HL6_partisan_right_favor")], na.rm=TRUE))/2)





###Creating mainstrem score 
usdata.wave2$mainstream <- ((rowSums(usdata.wave2[,c("HL1_mainstr_left_bias", "HL1_mainstr_left_favor", "HL2_mainstr_left_bias", "HL2_mainstr_left_favor", 
                                   "HL3_mainstr_left_bias", "HL3_mainstr_left_favor", "HL4_mainstr_left_bias", "HL4_mainstr_left_favor", "HL5_mainstr_left_bias", "HL5_mainstr_left_favor", "HL6_mainstr_left_bias", "HL6_mainstr_left_favor", "HL1_mainstr_right_bias", "HL1_mainstr_right_favor", "HL2_mainstr_right_bias", "HL2_mainstr_right_favor", "HL3_mainstr_right_bias", "HL3_mainstr_right_favor", "HL4_mainstr_right_bias", "HL4_mainstr_right_favor", "HL5_mainstr_right_bias", "HL5_mainstr_right_favor", "HL6_mainstr_right_bias", "HL6_mainstr_right_favor")], na.rm=TRUE))/2)

usdata.wave2$mainstream <- 5 - usdata.wave2$mainstream

###Creating false score 

usdata.wave2$false <- ((rowSums(usdata.wave2[,c("HL1_fake_left_acc", "HL1_fake_left_trust", "HL2_fake_left_acc", "HL2_fake_left_trust", 
                                   "HL3_fake_left_acc", "HL3_fake_left_trust", "HL4_fake_left_acc", "HL4_fake_left_trust", "HL5_fake_left_acc", "HL5_fake_left_trust", "HL6_fake_left_acc", "HL6_fake_left_trust", "HL1_fake_right_acc", "HL1_fake_right_trust", "HL2_fake_right_acc", "HL2_fake_right_trust", "HL3_fake_right_acc", "HL3_fake_right_trust", "HL4_fake_right_acc", "HL4_fake_right_trust", "HL5_fake_right_acc", "HL5_fake_right_trust", "HL6_fake_right_acc", "HL6_fake_right_trust")], na.rm=TRUE))/2)

usdata.wave2$false <- 5 - usdata.wave2$false




```


```{r}
####Hypo 1a
usdata.wave2$tr_factcheck <- as.factor(usdata.wave2$tr_factcheck)
###Hypo 1a - Misp
h1a1 <- lm(misp ~ age +gender + race + education + party.ID + tr_factcheck + political_interest, data = usdata.wave2 )
summary(h1a1)

###Hypo 1b - Skept 
h1b1 <- lm(skept ~ age + gender + race + education +  party.ID + tr_factcheck + political_interest, data = usdata.wave2 )
summary(h1b1)

###Hypo 1c
h1c1 <-lm(trust ~  age +gender + race + education +  party.ID + tr_factcheck + political_interest, data = usdata.wave2)
summary(h1c1)

###Hypo 2a False  
usdata.wave2$tr_medialit <- as.factor(usdata.wave2$tr_medialit)

H2a1 <-lm(false ~  age +gender + race + education +     party.ID + tr_medialit  + political_interest, data = usdata.wave2)
summary(H2a1)


###Hypo 2b Accurate News 

H2b1 <-lm(mainstream ~  age +gender + race + education +     party.ID + tr_medialit  + political_interest, data = usdata.wave2)
summary(H2b1)

##Hypo 2c Biased News 

H2c1 <-lm(hyperpartisan ~ age + gender + race + education +     party.ID + tr_medialit  + political_interest, data = usdata.wave2)
summary(H2c1)

###Hypo 2d Trust

H2d1 <- lm(trust ~ age + gender + race + education +     party.ID + tr_medialit  + political_interest, data = usdata.wave2)
summary(H2d1)

###Hypo 2e Skept 

H2e1 <-lm(skept ~  age + gender + race + education +     party.ID + tr_medialit  + political_interest, data = usdata.wave2)
summary(H2e1)

###Hypo 3a Trust 
usdata.wave2$tr_coverage <- as.factor(usdata.wave2$tr_coverage)
H3a1 <- lm(trust ~  age +gender + race + education +     party.ID + tr_coverage  + political_interest, data = usdata.wave2)
summary(H3a1)

###Hypo 3b Misper

H3b1 <- lm(misp ~  age +gender + race + education +     party.ID + tr_coverage  + political_interest, data = usdata.wave2)
summary(H3b1)

###Hypo 3c Skept 

H3c1 <- lm(skept ~ age + gender + race + education +     party.ID + tr_coverage  + political_interest, data = usdata.wave2)
summary(H3c1)



###Comparing 2 treatments 

###Hypo1 with 1 as reference group

tr_factcheck.coded <- relevel(as.factor(usdata.wave2$tr_factcheck),
                        ref = "1")

h1a2 <-lm(misp ~  age + gender + race + education + party.ID + tr_factcheck.coded + political_interest, data = usdata.wave2 )
summary(h1a2)

h1b2 <- lm(skept ~  age +gender + race + education + party.ID + tr_factcheck.coded + political_interest, data = usdata.wave2)
summary(h1b2)

h1c2 <-lm(trust ~  age +gender + race + education + party.ID + tr_factcheck.coded + political_interest, data = usdata.wave2)
summary(h1c2)

###Hypo2 with 1 as reference group
tr_medialit.recoded  <- relevel(as.factor(usdata.wave2$tr_medialit),
                        ref = "1")

H2a2 <-lm(false ~  age +gender + race + education +     party.ID + tr_medialit.recoded  + political_interest, data = usdata.wave2)
summary(H2a2)

H2b2 <-lm(mainstream ~  age +gender + race + education +     party.ID + tr_medialit.recoded  + political_interest, data = usdata.wave2)
summary(H2b2)

H2c2 <- lm(hyperpartisan ~  age +gender + race + education +     party.ID + tr_medialit.recoded  + political_interest, data = usdata.wave2)
summary(H2c2)


H2d2 <- lm(trust ~  age +gender + race + education +     party.ID + tr_medialit.recoded  + political_interest, data = usdata.wave2)
summary(H2d2)

H2e2 <- lm(skept ~  age +gender + race + education +     party.ID + tr_medialit.recoded  + political_interest, data = usdata.wave2)
summary(H2e2)

###Hypo3 with 1 as reference group
tr_coverage.recoded <- relevel(as.factor(usdata.wave2$tr_coverage),
                        ref = "1")

H3a2 <- lm(trust ~  age +gender + race + education +party.ID + tr_coverage.recoded  + political_interest, data = usdata.wave2)
summary(H3a2)

H3b2 <- lm(misp ~  age +gender + race + education +     party.ID + tr_coverage.recoded  + political_interest, data = usdata.wave2)
summary(H3b2)

H3c2 <- lm(skept ~ age + gender + race + education +     party.ID + tr_coverage.recoded  + political_interest, data = usdata.wave2)
summary(H3c2)

```

```{r}
###Exploratory Analysis 
usdata.wave2$tr_all <- as.factor(usdata.wave2$tr_all)

intent.medialit.usw2 <- lm(visit_medialit ~ age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(intent.medialit.usw2)

intent.news.usw2<- lm(visit_news ~ age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(intent.news.usw2)

intent.fake.usw2 <- lm(visit_fake ~age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(intent.fake.usw2)

intent.fact.usw2<- lm(visit_fact ~age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(intent.fact.usw2)

##Trust Cronbach Alpha
trust.data<- data.frame(usdata.wave2$Journalists, usdata.wave2$Fact.checkers, usdata.wave2$U.S..Government, usdata.wave2$University.Professors, usdata.wave2$Social.media, usdata.wave2$Traditional.media, usdata.wave2$Scientists)

cronbach.alpha(trust.data, na.rm = TRUE)


trust.journalist.w2 <- lm(Journalists ~age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(trust.journalist.w2)

trust.Fact.checkers.w2 <- lm(Fact.checkers ~age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(trust.Fact.checkers.w2)

trust.usgov.w2 <-  lm(U.S..Government ~age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(trust.usgov.w2)


trust.uni.profs.w2 <-  lm(University.Professors ~age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(trust.uni.profs.w2)

trust.socialmedia.w2 <-  lm(Social.media ~age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(trust.socialmedia.w2)

trust.traditionalmedia.w2 <-lm(Traditional.media ~age +gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(trust.traditionalmedia.w2)

trust.scientists.w2 <- lm(Scientists ~age + gender + race + education + party.ID + tr_all + political_interest, data= usdata.wave2)
summary(trust.scientists.w2)


###News Coverage on  false, mainstream and hyperpartisan news detection compared to CONTROL 

news.coverage.false <- lm(false ~age + gender + race + education + party.ID + tr_coverage + political_interest, data= usdata.wave2)
summary(news.coverage.false)

news.coverage.mainstream <- lm(mainstream ~age + gender + race + education + party.ID + tr_coverage + political_interest, data= usdata.wave2)
summary(news.coverage.mainstream)

news.coverage.hyperpartisan <- lm(hyperpartisan ~age + gender + race + education + party.ID + tr_coverage + political_interest, data= usdata.wave2)
summary(news.coverage.hyperpartisan)

###News Coverage on  false, mainstream and hyperpartisan news detection compared to 2 Treatment  

news.coverage.false2 <- lm(false ~age + gender + race + education + party.ID + tr_coverage.recoded + political_interest, data= usdata.wave2)
summary(news.coverage.false2)

news.coverage.mainstream2 <- lm(mainstream ~age + gender + race + education + party.ID + tr_coverage.recoded + political_interest, data= usdata.wave2)
summary(news.coverage.mainstream2)

news.coverage.hyperpartisan2 <- lm(hyperpartisan ~age + gender + race + education + party.ID + tr_coverage.recoded + political_interest, data= usdata.wave2)
summary(news.coverage.hyperpartisan2)

```

```{r}

usdata.wave2$tr_all <- as.factor(usdata.wave2$tr_all)
###Hypo 1a - Misp
us.w2.misp.all <- lm(misp ~ age +gender + race + education + party.ID + tr_all + political_interest, data = usdata.wave2 )
summary(us.w2.misp.all)

###Hypo 1b - Skept 
us.w2.skept.all <- lm(skept ~ age + gender + race + education +  party.ID + tr_all + political_interest, data = usdata.wave2 )
summary(us.w2.skept.all)

###Hypo 1c
us.w2.trust.all <-lm(trust ~  age +gender + race + education +  party.ID + tr_all + political_interest, data = usdata.wave2)
summary(us.w2.trust.all)

us.w2.models  <- list(us.w2.misp.all,us.w2.skept.all,us.w2.trust.all)

stargazer(us.w2.models, type = "latex", title = "Trust by Treatment Condition", dep.var.labels= c("Misperception", "Skepticism", "Trust" ), covariate.labels = c("age", "gender", "race", "education", "birth place", "Contextualized Media Coverage", "De-Contextualized Media Coverage", "Accountability Fact Checking","Correctability Fact Checking", "Bias News Media Literacy", "Fake News Media Literacy", "political interest"))


us.w2.plot1 <- plot_coefs(us.w2.misp.all,us.w2.skept.all,us.w2.trust.all, coefs = c("Contextualized Media Coverage" = "tr_all1", "De-Contextualized Media Coverage" = "tr_all2", "Accountability Fact Checking" = "tr_all3", "Correctability Fact Checking" = "tr_all4", "Bias News Media Literacy" = "tr_all5", "Fake News Media Literacy" = "tr_all6"), model.names = c("Misperceptions", "Skpeticism", "Trust"), legend.title = "Outcome") + ggtitle("All Respondents") 

us.w2.plot1

###Hypo 2a False  
usdata.wave2$tr_medialit <- as.factor(usdata.wave2$tr_medialit)

us.w2.false.all <-lm(false ~  age +gender + race + education +     party.ID + tr_all  + political_interest, data = usdata.wave2)
summary(us.w2.false.all)


###Hypo 2b Accurate News 

us.w2.mainstream.all <-lm(mainstream ~  age +gender + race + education +     party.ID + tr_all  + political_interest, data = usdata.wave2)
summary(us.w2.mainstream.all)

##Hypo 2c Biased News 

us.w2.hyperpartisan.all <-lm(hyperpartisan ~ age + gender + race + education +     party.ID + tr_all  + political_interest, data = usdata.wave2)
summary(us.w2.hyperpartisan.all)

us.w2.plot2 <- plot_coefs(us.w2.false.all,us.w2.mainstream.all,us.w2.hyperpartisan.all, coefs = c("Contextualized Media Coverage" = "tr_all1", "De-Contextualized Media Coverage" = "tr_all2", "Accountability Fact Checking" = "tr_all3", "Correctability Fact Checking" = "tr_all4", "Bias News Media Literacy" = "tr_all5", "Fake News Media Literacy" = "tr_all6"), model.names = c("False", "Mainsteam", "Hyperpartisan"), legend.title = "Outcome", colors = "Qual1") + ggtitle("All Respondents")
us.w2.plot2

us.w2.plot3 <- plot_coefs(intent.fact.usw2,intent.fake.usw2,intent.medialit.usw2, intent.news.usw2, coefs = c("Contextualized Media Coverage" = "tr_all1", "De-Contextualized Media Coverage" = "tr_all2", "Accountability Fact Checking" = "tr_all3", "Correctability Fact Checking" = "tr_all4", "Bias News Media Literacy" = "tr_all5", "Fake News Media Literacy" = "tr_all6"), model.names = c("Fact Checking Websites", "Fake News Website", "Media Literacy Website", "News Website"), legend.title = "Outcome", colors = "Qual2") + ggtitle("All Respondents") 
us.w2.plot3

us.w2.plot4 <- plot_coefs(trust.Fact.checkers.w2,trust.journalist.w2,trust.scientists.w2,trust.socialmedia.w2, trust.traditionalmedia.w2,trust.uni.profs.w2, trust.usgov.w2, coefs = c("Contextualized Media Coverage" = "tr_all1", "De-Contextualized Media Coverage" = "tr_all2", "Accountability Fact Checking" = "tr_all3", "Correctability Fact Checking" = "tr_all4", "Bias News Media Literacy" = "tr_all5", "Fake News Media Literacy" = "tr_all6"), model.names = c("Fact Checkers", "Journalists", "Scientists", "Social Media", "Traditional Media","University Professors", "U.S. Government"), legend.title = "Outcome", colors = "Qual3") + ggtitle("All Respondents") 
us.w2.plot4

```

```{r}
usa.wave2.mc.n <- usdata.wave2 %>% filter(mani_check_pass == "Pass") %>% count(mani_check_pass)
usa.wave2.mc.n

write.csv(usdata.wave2, "/Users/brianaitken/Desktop/5.18 Updated US W2 Final dataset.csv")

```